#!/usr/bin/env node

/**
 * `parton` CLI — manages remote-frame bindings in a host repo.
 *
 *   parton add <name> <origin>   Fetch <origin>/__remote/manifest.json
 *                                and download types. Generates:
 *                                  src/remote/<name>/types.ts
 *                                  src/remote/<name>/index.ts
 *
 *   parton update <name>         Re-run the fetch using the origin
 *                                recorded in the generated index.ts.
 *                                Useful after the remote app added
 *                                new specs or updated capability
 *                                schemas.
 *
 *   parton remove <name>         Delete src/remote/<name>/.
 *
 * Output style mirrors shadcn — a few small files committed into
 * the consumer's repo so the types are local, version-pinned, and
 * editable in place if the remote disappears.
 */

import { mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises"
import { join, resolve } from "node:path"

const cwd = process.cwd()

function usage() {
  console.error(`Usage:
  parton add <name> <origin>     Install bindings for a remote app.
  parton update <name>           Re-fetch bindings using the saved origin.
  parton remove <name>           Delete a remote binding directory.
  parton list                    Show installed remotes.`)
  process.exit(1)
}

function logInfo(msg) {
  process.stdout.write(`${msg}\n`)
}

function logError(msg) {
  process.stderr.write(`error: ${msg}\n`)
}

function pascalCase(input) {
  return input
    .split(/[-_/.\s]+/)
    .filter(Boolean)
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
    .join("")
}

function isValidName(name) {
  return /^[a-z][a-z0-9-]*$/.test(name)
}

function isValidOrigin(origin) {
  try {
    const url = new URL(origin)
    return (url.protocol === "http:" || url.protocol === "https:") && url.pathname === "/"
  } catch {
    return false
  }
}

async function fetchJson(url) {
  const res = await fetch(url)
  if (!res.ok) {
    throw new Error(`fetch ${url} failed: HTTP ${res.status}`)
  }
  return res.json()
}

async function fetchText(url) {
  const res = await fetch(url)
  if (!res.ok) {
    throw new Error(`fetch ${url} failed: HTTP ${res.status}`)
  }
  return res.text()
}

function targetDir(name) {
  return resolve(cwd, "src", "remote", name)
}

const HEADER_DIRECTIVE_PREFIX = "// parton:remote "

function buildIndexFile(name, origin, manifest) {
  const lines = []
  lines.push(
    `// AUTO-GENERATED by \`parton add ${name} ${origin}\`. Re-run \`parton update ${name}\` to refresh.`,
  )
  lines.push(`${HEADER_DIRECTIVE_PREFIX}name=${name} origin=${origin}`)
  lines.push("")
  lines.push(`import { remote } from "@parton/framework"`)

  const typedSpecs = manifest.specs.filter((s) => s.capabilityType)
  if (typedSpecs.length > 0) {
    const typeNames = [...new Set(typedSpecs.map((s) => s.capabilityType))]
    lines.push(`import type { ${typeNames.join(", ")} } from "./types.ts"`)
  }
  lines.push("")

  lines.push(`const ORIGIN = ${JSON.stringify(origin)}`)
  lines.push(`const NAMESPACE = ${JSON.stringify(name)}`)
  lines.push("")

  for (const spec of manifest.specs) {
    if (spec.capabilityType) {
      lines.push(
        `export const ${spec.exportName} = remote<${spec.capabilityType}>({`,
      )
    } else {
      lines.push(`export const ${spec.exportName} = remote({`)
    }
    lines.push(`  origin: ORIGIN,`)
    lines.push(`  selector: ${JSON.stringify(spec.selector)},`)
    lines.push(`  namespace: NAMESPACE,`)
    lines.push(`})`)
    lines.push("")
  }

  return lines.join("\n")
}

async function cmdAdd(args) {
  const [name, origin] = args
  if (!name || !origin) usage()
  if (!isValidName(name)) {
    logError(`name "${name}" must be kebab-case (a-z, 0-9, '-', starting with a letter)`)
    process.exit(1)
  }
  if (!isValidOrigin(origin)) {
    logError(`origin "${origin}" must be a bare http(s):// URL (no path)`)
    process.exit(1)
  }
  const cleanOrigin = origin.replace(/\/$/, "")

  logInfo(`Fetching manifest from ${cleanOrigin}/__remote/manifest.json`)
  const manifest = await fetchJson(`${cleanOrigin}/__remote/manifest.json`)
  if (!manifest || typeof manifest !== "object" || !Array.isArray(manifest.specs)) {
    logError(`malformed manifest from ${cleanOrigin}`)
    process.exit(1)
  }

  logInfo(`Fetching types from ${cleanOrigin}/__remote/types.d.ts`)
  let typesContent
  try {
    typesContent = await fetchText(`${cleanOrigin}/__remote/types.d.ts`)
  } catch (err) {
    logInfo(`  (no types file: ${err.message}) — bindings will be untyped`)
    typesContent = "// no types declared by the remote\nexport {}\n"
  }

  const dir = targetDir(name)
  await mkdir(dir, { recursive: true })

  const typesPath = join(dir, "types.ts")
  const indexPath = join(dir, "index.ts")

  await writeFile(typesPath, typesContent, "utf8")
  await writeFile(indexPath, buildIndexFile(name, cleanOrigin, manifest), "utf8")

  logInfo(`Wrote ${typesPath}`)
  logInfo(`Wrote ${indexPath}`)
  logInfo(`Bound ${manifest.specs.length} spec(s) from ${cleanOrigin}.`)
}

async function cmdUpdate(args) {
  const [name] = args
  if (!name) usage()
  const dir = targetDir(name)
  let existing
  try {
    existing = await readFile(join(dir, "index.ts"), "utf8")
  } catch {
    logError(`no installed remote at ${dir}`)
    process.exit(1)
  }
  const directive = existing
    .split("\n")
    .find((l) => l.startsWith(HEADER_DIRECTIVE_PREFIX))
  if (!directive) {
    logError(`no \`${HEADER_DIRECTIVE_PREFIX}\` directive in ${join(dir, "index.ts")}`)
    process.exit(1)
  }
  const fields = Object.fromEntries(
    directive
      .slice(HEADER_DIRECTIVE_PREFIX.length)
      .split(/\s+/)
      .filter(Boolean)
      .map((kv) => {
        const eq = kv.indexOf("=")
        return eq < 0 ? [kv, ""] : [kv.slice(0, eq), kv.slice(eq + 1)]
      }),
  )
  if (!fields.origin) {
    logError(`directive missing origin= in ${dir}`)
    process.exit(1)
  }
  await cmdAdd([name, fields.origin])
}

async function cmdRemove(args) {
  const [name] = args
  if (!name) usage()
  const dir = targetDir(name)
  await rm(dir, { recursive: true, force: true })
  logInfo(`Removed ${dir}`)
}

async function cmdList() {
  const root = resolve(cwd, "src", "remote")
  let entries
  try {
    entries = await readdir(root, { withFileTypes: true })
  } catch {
    logInfo("No remotes installed (src/remote/ does not exist).")
    return
  }
  for (const e of entries) {
    if (!e.isDirectory()) continue
    const indexPath = join(root, e.name, "index.ts")
    let directive = ""
    try {
      const body = await readFile(indexPath, "utf8")
      const line = body.split("\n").find((l) => l.startsWith(HEADER_DIRECTIVE_PREFIX))
      if (line) directive = line.slice(HEADER_DIRECTIVE_PREFIX.length)
    } catch {
      directive = "(no index.ts)"
    }
    logInfo(`  ${e.name}: ${directive}`)
  }
}

async function main() {
  const [cmd, ...rest] = process.argv.slice(2)
  if (!cmd) usage()
  try {
    switch (cmd) {
      case "add":
        await cmdAdd(rest)
        break
      case "update":
        await cmdUpdate(rest)
        break
      case "remove":
        await cmdRemove(rest)
        break
      case "list":
        await cmdList()
        break
      default:
        usage()
    }
  } catch (err) {
    logError(err instanceof Error ? err.message : String(err))
    process.exit(1)
  }
}

main()
