// AUTO-GENERATED by `parton add magento http://localhost:5181`. Re-run `parton update magento` to refresh.
// parton:remote name=magento origin=http://localhost:5181

import { remote } from "@parton/framework"
import type { PaymentCap } from "./types.ts"

// `MAGENTO_REMOTE_ORIGIN` lets a test harness (or a worktree with
// remapped ports) point these bindings at a differently-addressed
// instance of the same remote without regenerating the file. The
// env var name derives from the install name (`magento`).
const ORIGIN = process.env.MAGENTO_REMOTE_ORIGIN ?? "http://localhost:5181"
const NAMESPACE = "magento"

export const MagentoCheckoutStep = remote({
  origin: ORIGIN,
  path: "/remote/magento-checkout-step",
  namespace: NAMESPACE,
})

export const MagentoGreeting = remote({
  origin: ORIGIN,
  path: "/remote/magento-greeting",
  namespace: NAMESPACE,
})

export const MagentoPaymentSummary = remote<PaymentCap>({
  origin: ORIGIN,
  path: "/remote/magento-payment-summary",
  namespace: NAMESPACE,
})

export const MagentoStocks = remote({
  origin: ORIGIN,
  path: "/remote/magento-stocks",
  namespace: NAMESPACE,
})

// Paint-tier surfaces — grant baked into the binding (a binding is
// origin + page path + grant set; the grant is a property of the
// install). Hand-extended pending manifest tier claims.
export const MagentoPaintSummary = remote({
  origin: ORIGIN,
  path: "/remote/paint-summary",
  namespace: NAMESPACE,
  grant: "paint",
})

export const MagentoPaintMixed = remote({
  origin: ORIGIN,
  path: "/remote/paint-mixed",
  namespace: NAMESPACE,
  grant: "paint",
})

// Interactive-tier surface (increment 5). The same page bound twice:
// the interactive install, and a paint-granted install proving the
// interactive rows degrade under the narrower grant.
export const MagentoInteractivePanel = remote({
  origin: ORIGIN,
  path: "/remote/interactive-panel",
  namespace: NAMESPACE,
  grant: "interactive",
})

export const MagentoInteractivePanelPaint = remote({
  origin: ORIGIN,
  path: "/remote/interactive-panel",
  namespace: NAMESPACE,
  grant: "paint",
})

// Bound-cells surface — declares `cells: { cart: required, locale }`;
// the host binds RESOLVED cells at the call site. Ungoverned (full
// trust): bound cells are orthogonal to grants.
export const MagentoCartNote = remote({
  origin: ORIGIN,
  path: "/remote/cart-note",
  namespace: NAMESPACE,
})

/** The remote origin, for host modules that address it directly
 *  (the remote-cell demo's `remoteCell({origin})`). */
export const MAGENTO_ORIGIN = ORIGIN
