// AUTO-GENERATED by `parton add magento http://localhost:5181`. Re-run `parton update magento` to refresh.
// parton:remote name=magento origin=http://localhost:5181

import { remote } from "@parton/framework"
import type { PaymentCap } from "./types.ts"

const ORIGIN = "http://localhost:5181"
const NAMESPACE = "magento"

export const CartSummary = remote({
  origin: ORIGIN,
  selector: "cart-summary",
  namespace: NAMESPACE,
})

export const MagentoCheckoutStep = remote({
  origin: ORIGIN,
  selector: "magento-checkout-step",
  namespace: NAMESPACE,
})

export const MagentoGreeting = remote({
  origin: ORIGIN,
  selector: "magento-greeting",
  namespace: NAMESPACE,
})

export const MagentoPaymentSummary = remote<PaymentCap>({
  origin: ORIGIN,
  selector: "magento-payment-summary",
  namespace: NAMESPACE,
})

export const MagentoStocks = remote({
  origin: ORIGIN,
  selector: "magento-stocks",
  namespace: NAMESPACE,
})
