import { describe, expect, it } from "vitest"
import { AccessRecorder } from "../access-recorder.js"
import { createProxy } from "../proxy-node.js"
import { compileQuery } from "../query-compiler.js"
import { fetchSchema } from "../schema.js"

const POKEAPI_ENDPOINT = "https://beta.pokeapi.co/graphql/v1beta"

describe("Query output inspection", { timeout: 15000 }, () => {
  it("prints the exact query generated by a component render", async () => {
    const schema = await fetchSchema(POKEAPI_ENDPOINT)

    function PokemonCard(pokemon: any) {
      return {
        name: pokemon.name.value,
        height: pokemon.height.value,
        sprite: pokemon.pokemon_v2_pokemonsprites.map((s: any) => s.sprites.value),
        types: pokemon.pokemon_v2_pokemontypes.map((t: any) => t.pokemon_v2_type.name.value),
      }
    }

    const recorder = new AccessRecorder()
    PokemonCard(createProxy(schema, "pokemon_v2_pokemon", recorder) as any)
    const query = compileQuery(recorder.getAccessTree(), "pokemon_v2_pokemon", {
      limit: 3,
    })

    console.log("\n--- Generated Query ---\n" + query + "\n--- End Query ---\n")

    const response = await fetch(POKEAPI_ENDPOINT, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ query }),
    })
    const json = (await response.json()) as {
      data: Record<string, any[]>
      errors?: any[]
    }
    expect(json.errors).toBeUndefined()
    expect(json.data.pokemon_v2_pokemon).toHaveLength(3)
  })
})
