/**
 * /remote-frame-crossorigin-demo — true cross-origin `<RemoteFrame>`.
 *
 * The cards below are rendered by `e2e-magento` on port 5181. The
 * host imports typed bindings generated by `yarn parton add magento
 * http://localhost:5181` (see `src/remote/magento/`) and uses them
 * like any other component — capability shape is enforced at
 * compile time.
 *
 * To exercise this page, both dev servers must be running:
 *   - `yarn dev` (this app, port 5173)
 *   - `yarn dev:magento` (the remote, port 5181)
 */

import { parton, searchParam, type RenderArgs } from "@parton/framework"
import { Frame } from "@parton/framework/lib/frame.tsx"
import { Suspense } from "react"
import { Card, CardContent } from "@parton/copies/components/ui/card"
import { RemoteRefreshButton } from "../components/remote-refresh-button.tsx"
import { CheckoutStepNav } from "../components/checkout-step-nav.tsx"
import {
  MagentoCheckoutStep,
  MagentoGreeting,
  MagentoPaymentSummary,
  MagentoStocks,
} from "../../remote/magento"

/** Wrapper parton — reads `?step=` from the frame URL and threads it
 *  into MagentoCheckoutStep's searchParams. The remote spec's `vary`
 *  reads the same param, so when the frame URL changes the binding
 *  re-fetches with the new step.
 *
 *  Demonstrates: navigating within a `<Frame>` to a different variant
 *  of the SAME bound remote, without reloading the host or affecting
 *  other frames. The frame URL is the navigation axis; the parton's
 *  vary is the bridge.
 */
const RemoteCheckoutFrame = parton(
  function RemoteCheckoutFrameRender({ step }: { step: string } & RenderArgs) {
    return (
      <Suspense
        fallback={
          <Card className="mb-2 p-4" data-testid="rfxd-checkout-fallback">
            <CardContent className="px-0 italic text-muted-foreground">
              Loading checkout step…
            </CardContent>
          </Card>
        }
      >
        <MagentoCheckoutStep searchParams={{ step }} />
      </Suspense>
    )
  },
  {
    selector: "remote-checkout-frame",
    schema: () => ({ step: searchParam("step", "shipping") }),
  },
)

export const RemoteFrameCrossOriginDemoPage = parton(
  function RemoteFrameCrossOriginDemoRender() {
    return (
      <>
        <header className="mb-4" data-testid="rfxd-header">
          <div className="mb-2 flex flex-wrap gap-2">
            <RemoteRefreshButton selector="magento-stocks" label="Refresh stocks (cross-origin)" />
            <RemoteRefreshButton selector="magento-payment-summary" label="Refresh payment" />
          </div>
          <h1 className="text-2xl font-semibold">Cross-Origin Remote Frame Demo</h1>
          <p className="text-sm text-muted-foreground">
            Host rendered at <code>{new Date().toISOString()}</code>.
          </p>
          <p className="mt-2 text-xs text-muted-foreground">
            Bindings under <code>src/remote/magento/</code> were generated by{" "}
            <code>yarn parton add magento http://localhost:5181</code>. The host
            renders the typed components below; the framework fetches their
            Flight bytes from the <code>e2e-magento</code> dev server, rewrites
            module references to absolute URLs at the remote's origin, decodes,
            and stitches the result into this response. If you don't see content
            below, the <code>e2e-magento</code> dev server isn't running.
          </p>
        </header>

        <Suspense
          fallback={
            <Card className="mb-2 p-4" data-testid="rfxd-greeting-fallback">
              <CardContent className="px-0 italic text-muted-foreground">
                Fetching cross-origin greeting…
              </CardContent>
            </Card>
          }
        >
          <MagentoGreeting />
        </Suspense>

        <Suspense
          fallback={
            <Card className="mb-2 p-4" data-testid="rfxd-stocks-fallback">
              <CardContent className="px-0 italic text-muted-foreground">
                Fetching cross-origin stock ticker…
              </CardContent>
            </Card>
          }
        >
          <MagentoStocks />
        </Suspense>

        <Suspense
          fallback={
            <Card className="mb-2 p-4" data-testid="rfxd-payment-fallback">
              <CardContent className="px-0 italic text-muted-foreground">
                Fetching capability-scoped payment summary…
              </CardContent>
            </Card>
          }
        >
          <MagentoPaymentSummary
            capability={{
              cart_id: "demo-cart-7f3a9",
              currency: "EUR",
              total: 127.45,
            }}
          />
        </Suspense>

        <Frame name="checkout" initialUrl="/?step=shipping">
          <CheckoutStepNav />
          <RemoteCheckoutFrame />
        </Frame>

        <footer className="mt-4 text-xs text-muted-foreground" data-testid="rfxd-footer">
          Footer rendered at <code>{new Date().toISOString()}</code>. The host
          paints chrome immediately; each cross-origin fetch resolves
          independently and stitches in via its Suspense boundary.
        </footer>
      </>
    )
  },
  { match: "/remote-frame-crossorigin-demo" },
)
